[workspace]
resolver = "3"

members = ["rpcbind-rs", "rpcbind-server"]

[workspace.dependencies]
bytes = "1.10.1"
onc-rpc = { version = "0.3.1", features = ["bytes"] }
facet = "0.27.16"
facet-xdr = "0.1.19"

rpcbind-rs.path = "rpcbind-rs"
